### ISSUE TITLE
Update the README to reflect potential migration steps

### ISSUE THREAD

**Issue by jamezp** [resteasy/resteasy-guice#16]
Things like the new Maven GAV should be listed as well as the package renames. Other things may come up while looking through this.

**Comment by iain-davis** [comment]
I took an initial pass at adding some guidance to the readme.md. Let me know if this reasonably close to what you had in mind: https://github.com/iain-davis/resteasy-guice/tree/main

If it serves, I'll issue a pull-request for it.

**Comment by jamezp** [comment]
Looks good to me @iain-davis. Feel free to send up a PR, thank you!
